if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if [[ -f $HOME/.env.private ]]; then
  source $HOME/.env.private
fi

AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE=1

